#ifndef CSO_MESSAGE_DEFINE_H
#define CSO_MESSAGE_DEFINE_H

#define LENGTH_IV			12
#define LENGTH_AUTHEN_TAG	16
#define LENGTH_SIGN			32
#define LENGTH_SIGN_RSA		512
#define LENGTH_TICKET_TOKEN	32
#define LENGTH_KEY		    32

#endif //!CSO_MESSAGE_DEFINE_H